module.exports = {
    ROOM1:'W3N29',
    // creep 类型
    CREEP_TYPE_HARVESTER: 'harvester',
    CREEP_TYPE_CARRY: 'carry',
    CREEP_TYPE_UPGRADER: 'upgrader',
    CREEP_TYPE_WORK: 'work',
    CREEP_TYPE_BUILDER: 'builder',
    CREEP_TYPE_LITTER: 'litter',

    // creep身体构造
    CREEP_BODY_HARVESTER: [WORK, WORK, WORK, WORK, WORK, WORK, CARRY,MOVE, MOVE, MOVE],
    CREEP_BODY_CARRY: [CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE, MOVE, MOVE],
    CREEP_BODY_UPGRADER: [WORK, WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE],
    CREEP_BODY_BUILDER: [WORK, WORK, WORK, WORK, CARRY, CARRY, CARRY, CARRY, MOVE, MOVE, MOVE, MOVE],
    // 能量不足时body
    CREEP_BODY_NO_ENERGY:[WORK,WORK,CARRY,MOVE],


    // container 位置
    STRUCTURE_CONTAINER_TOP_POSITION: [23,8],
    STRUCTURE_CONTAINER_CENTER_POSITION: [21,19],
    STRUCTURE_CONTAINER_BOTTOM_POSITION: [10,27],
    // 房间顶部资源池id
    STRUCTURE_SOURCE_TOP_ID: "5bbcacb49099fc012e6360d5",

    // 房间storage的ID
    STRUCTURE_STORAGE_ID: '5d3b9b6aa48c1b74452bc840'
}